# Generated by Django 4.1.1 on 2022-09-07 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='position',
            field=models.IntegerField(blank=True, choices=[(0, 'System admin'), (1, 'Sub admin'), (2, 'Accountant'), (3, 'AR Officer'), (4, 'AP Officer'), (5, 'Production manager'), (6, 'Purchase manager'), (7, 'Stock manager'), (8, 'Sale man'), (10, 'Inquiries')], default=10, verbose_name='position'),
        ),
    ]
