# Generated by Django 3.2.15 on 2022-09-09 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_user_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='position',
            field=models.CharField(blank=True, choices=[('System admin', 'System admin'), ('Sub admin', 'Sub admin'), ('HR', 'HR'), ('Inquiries', 'Inquiries')], default='INQUIRIES', max_length=150, verbose_name='position'),
        ),
    ]
